# Generated by Django 3.0.8 on 2020-07-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
