# Generated by Django 3.0.8 on 2020-07-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0002_auto_20200731_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-id']},
        ),
    ]
